### ISSUE TITLE
AE2 network connection not working after server restart

### ISSUE THREAD

**Issue by theron61** [thraaawn/CompactMachines#78]
I am running version 1.17 with AE2 rv2,beta7 and have an odd issue where AE2 connections need to be broken and replaced on the outside of the compact machine to restore connectivity.  This only seems to happen on server restart.

What can I do to help troubleshoot this?

**Comment by thraaawn** [comment]
I did not manage to reproduce this. Are they visually connected?
And do you have an idea on how i could trigger this behavior?

**Comment by theron61** [comment]
I think it might have been due to the security station.  I'll test further.

**Comment by NonniT** [comment]
I'm having this same issue, running AE2 RV8 and 1.17.

**Comment by Zaflis** [comment]
Have you tested RF tunnels inside a compact machine? I thought they weren't active on server restart, but can't say 100% on it.

**Comment by theron61** [comment]
The issue, for me, manifests as the network appearing to be connected with existing end points showing as active in Walia.  I have to break and re-add the cable on the outside of the Compact Machine to correct this.  I am going to test with the Security Station disabled to see if that might be the culprit.

**Comment by psychofad** [comment]
I am also seeing this behavior....again....I thought this was fixed in a previous build.  Not sure if it is relevant but I am also using the security station (required for wireless) and the cables are going into an upgraded (nether star) machine that is quantum linked with other machines.  Everything is chunkloaded.

**Comment by Sj212** [comment]
Security terminal definitely seems like the cause, as I was also having this issue. Adding an unassigned biometric card appears to have solved the issue though, along with replacing the terminal.

**Comment by thraaawn** [comment]
Same as #79, should be resolved with the release of 1.18.

**Comment by guillaumearm** [comment]
It seems this bug is back in `compactmachines3-1.12.2-3.0.12-b215`

**Comment by davenonymous** [comment]
Compact Machines 3 never had AE2 support.
